name: Release HTTP client to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.8
