# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: HTTP API client

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      env:
        FORCE_COLOR: 2
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with ruff
      env:
        FORCE_COLOR: 2
      run: |
        ruff check
    - name: Check typing with mypy
      env:
        FORCE_COLOR: 2
      run: |
        mypy --install-types --non-interactive .
    - name: Format code with ruff
      env:
        FORCE_COLOR: 2
      run: |
        ruff format --diff
    - name: Test with pytest
      env:
        FORCE_COLOR: 2
      run: |
        pytest -v
